package org.grida.coreapi.domain.support

enum class TransactionPropagationLevel {
    PROPAGATION_REQUIRED,
    PROPAGATION_SUPPORTS,
    PROPAGATION_MANDATORY,
    PROPAGATION_REQUIRES_NEW,
    PROPAGATION_NOT_SUPPORTED,
    PROPAGATION_NEVER,
    PROPAGATION_NESTED,
}

enum class TransactionIsolationLevel {
    ISOLATION_DEFAULT,
    ISOLATION_READ_UNCOMMITTED,
    ISOLATION_READ_COMMITTED,
    ISOLATION_REPEATABLE_READ,
    ISOLATION_SERIALIZABLE,
}
